### ISSUE TITLE
Destroying an item while a dialogue is open throws java.lang.IndexOutOfBoundsException: Index -3 out of bounds for length 2

### ISSUE THREAD

**Issue by tilkinsc** [titandino/darkan-world-server#61]
I was trying to destroy white hare meat and had a dialogue open at the same time. Doesnt happen every time, moreso intermittently on the same dialogue.

```
ERROR! THREAD NAME: World Pool-1-thread-1
java.lang.IndexOutOfBoundsException: Index -3 out of bounds for length 2
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at com.rs.game.player.content.dialogue.Dialogue.getNext(Dialogue.java:263)
	at com.rs.game.player.content.dialogue.Conversation.process(Conversation.java:290)
	at com.rs.net.decoders.handlers.impl.interfaces.IFContinueHandler.handle(IFContinueHandler.java:42)
	at com.rs.net.decoders.handlers.impl.interfaces.IFContinueHandler.handle(IFContinueHandler.java:1)
	at com.rs.game.player.Player.processPackets(Player.java:3781)
	at com.rs.game.player.Player.processEntity(Player.java:978)
	at com.rs.cores.WorldThread.run(WorldThread.java:76)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by titandino** [comment]
Fixed in current dev branch

**Comment by tilkinsc** [comment]
Wow! Such finesse!
